# Generated by Django 5.2 on 2025-05-14 21:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associado',
            name='endereco',
            field=models.CharField(help_text='Formato: Cidade, Rua, N° (Exemplo: Belo Horizonte, Rua Mayrink, 44)', max_length=255, validators=[django.core.validators.RegexValidator(message='O endereço deve seguir o formato: Cidade, Rua, Número (Exemplo: Belo Horizonte, Rua Mayrink, 44)', regex='^.+,\\s*.+,\\s*\\d+$')], verbose_name='Endereço'),
        ),
    ]
