# Generated by Django 5.2 on 2025-05-14 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avalicao', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avaliacao',
            options={'ordering': ['-dat_avaliacao'], 'verbose_name': 'Availiallos', 'verbose_name_plural': 'Availiallos'},
        ),
        migrations.AlterField(
            model_name='avaliado',
            name='is_associate',
            field=models.BooleanField(default=False, verbose_name='É associado'),
        ),
    ]
