# Generated by Django 5.2 on 2025-05-14 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avalicao', '0002_alter_avaliacao_options_alter_avaliado_is_associate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avalioracao',
            fields=[
                ('pk_avalioracao', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('dat_avaliacao', models.DateField(verbose_name='Data da Avalicao')),
                ('profundidade', models.IntegerField(choices=[(-9, '-9'), (-3, '-3'), (-1, '-1'), (0, '0'), (1, '+1'), (3, '+3'), (9, '+9')], verbose_name='Profundidade')),
                ('domínio_vocabular', models.IntegerField(choices=[(-9, '-9'), (-3, '-3'), (-1, '-1'), (0, '0'), (1, '+1'), (3, '+3'), (9, '+9')], verbose_name='Domínio Vocabular')),
                ('estrutura_didatica', models.IntegerField(choices=[(-9, '-9'), (-3, '-3'), (-1, '-1'), (0, '0'), (1, '+1'), (3, '+3'), (9, '+9')], verbose_name='Estrutura Didática')),
                ('presenca', models.IntegerField(choices=[(-9, '-9'), (-3, '-3'), (-1, '-1'), (0, '0'), (1, '+1'), (3, '+3'), (9, '+9')], verbose_name='Presença')),
                ('cultura_repertorio', models.IntegerField(choices=[(-9, '-9'), (-3, '-3'), (-1, '-1'), (0, '0'), (1, '+1'), (3, '+3'), (9, '+9')], verbose_name='Cultura e Repertório')),
                ('velocidade_ritmo', models.IntegerField(choices=[(-9, '-9'), (-3, '-3'), (-1, '-1'), (0, '0'), (1, '+1'), (3, '+3'), (9, '+9')], verbose_name='Velocidade de Raciocínio e Ritmo de Fala')),
                ('preparacao', models.IntegerField(choices=[(-9, '-9'), (-3, '-3'), (-1, '-1'), (0, '0'), (1, '+1'), (3, '+3'), (9, '+9')], verbose_name='Esforço / Preparação / Setting')),
                ('carisma', models.IntegerField(choices=[(-9, '-9'), (-3, '-3'), (-1, '-1'), (0, '0'), (1, '+1'), (3, '+3'), (9, '+9')], verbose_name='Carisma')),
                ('opi_avaliador', models.IntegerField(choices=[(-9, '-9'), (-3, '-3'), (-1, '-1'), (0, '0'), (1, '+1'), (3, '+3'), (9, '+9')], verbose_name='Opinião do avaliador')),
                ('contexto', models.IntegerField(choices=[(-9, '-9'), (-3, '-3'), (-1, '-1'), (0, '0'), (1, '+1'), (3, '+3'), (9, '+9')], verbose_name='Contexto')),
                ('recorte', models.IntegerField(choices=[(-9, '-9'), (-3, '-3'), (-1, '-1'), (0, '0'), (1, '+1'), (3, '+3'), (9, '+9')], verbose_name='Qualidade do Recorte Temático')),
                ('obs', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('fk_avaliado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Oracao', to='avalicao.avaliado')),
                ('fk_avaliador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Oracao', to='avalicao.avaliador')),
            ],
            options={
                'verbose_name': 'Availiallos',
                'verbose_name_plural': 'Availiallos',
                'ordering': ['-dat_avaliacao'],
            },
        ),
    ]
